#!/usr/bin/env bash

shopt -s nullglob globstar

if [[ -n $WAYLAND_DISPLAY ]]; then
	dmenu='dmenu-wl'
elif [[ -n $DISPLAY ]]; then
	dmenu='dmenu'
else
	echo "Error: No Wayland or X11 display detected" >&2
	exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password_file=$(printf '%s\n' "${password_files[@]}" | "$dmenu" -c "$@")

[[ -n $password_file ]] || exit

gpg_is_cached=$(gpg-connect-agent 'keyinfo --list' /bye 2>/dev/null | awk '{if($7==1){print 1}}')

if [[ $gpg_is_cached == 1 ]]; then
    pass show -c "$password_file" 2>/dev/null
else
    st -c 'term-float' -T 'pass pin entry' -g 68x13 -e pass show -c "$password_file" 2>/dev/null && pass show -c "$password_file" 2>/dev/null
fi
